/* Skill Saga — Learn flow completion: Class -> Subject -> Chapter -> Topic -> Lesson -> Practice */
(function(){
'use strict';
var C={board:'CBSE',status:'Live'};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function db(){return window.cloudDb||null} function shell(x){if(typeof window.shell==='function')window.shell(x)}
function loading(t){shell('<div class="row"><button class="back" onclick="window.go(\'learn\')">‹</button><div><h1 style="margin:0">Learn</h1><div class="muted">'+esc(t||'Loading…')+'</div></div></div><div class="card" style="margin-top:18px;text-align:center">Please wait…</div>')}
function empty(t,back){shell('<div class="row"><button class="back" onclick="'+back+'">‹</button><div><h1 style="margin:0">'+esc(t)+'</h1><div class="muted">Content will appear here when published.</div></div></div><div class="card" style="margin-top:18px">No live content found for this selection yet.</div>')}
async function q(coll,filters){var d=db();if(!d)return [];var r=d.collection(coll);(filters||[]).forEach(function(f){r=r.where(f[0],f[1],f[2])});try{var s=await r.get();return s.docs.map(function(x){return {id:x.id,...x.data()}})}catch(e){console.warn('Learn read failed',coll,e);return []}}
function uniq(a,key){var m={},o=[];(a||[]).forEach(function(x){var k=String(x[key]||'').trim();if(k&&!m[k]){m[k]=1;o.push(k)}});return o}
async function classes(){loading('Choose your class');var rows=await q('curriculum',[['board','==',C.board],['status','==',C.status]]);if(!rows.length)rows=await q('curriculum',[['board','==',C.board]]);var cs=uniq(rows,'class').sort(function(a,b){return parseInt(a)-parseInt(b)});if(!cs.length)cs=Array.from({length:12},function(_,i){return String(i+1)});shell('<div class="row"><button class="back" onclick="window.go(\'home\')">‹</button><div><h1 style="margin:0">Learn</h1><div class="muted">Choose your class</div></div></div><div class="section"><b>Academic</b><span>'+esc(C.board)+'</span></div><div class="ss-learn-classes">'+cs.map(function(c){return '<button class="ss-class" onclick="window.ssLearnSubjects(\''+esc(c).replace(/'/g,"\\'")+'\')">Class '+esc(c)+'</button>'}).join('')+'</div><div class="ss-final-note">Academic learning follows Class → Subject → Chapter → Topic → Lesson → Practice.</div>')}
async function subjects(cls){loading('Class '+cls+' · Subjects');var rows=await q('curriculum',[['board','==',C.board],['class','==',cls]]);var ss=uniq(rows,'subject').sort();if(!ss.length)return empty('Class '+cls,'window.ssLearnClasses()');shell('<div class="row"><button class="back" onclick="window.ssLearnClasses()">‹</button><div><h1 style="margin:0">Class '+esc(cls)+'</h1><div class="muted">Choose a subject</div></div></div><div class="ss-subjects" style="margin-top:16px">'+ss.map(function(s){return '<button class="ss-subject" onclick="window.ssLearnChapters(\''+esc(cls).replace(/'/g,"\\'")+'\',\''+esc(s).replace(/'/g,"\\'")+'\')"><div class="i">📘</div><b>'+esc(s)+'</b><small>Chapters & topics</small></button>'}).join('')+'</div>')}
async function chapters(cls,sub){loading(sub+' · Chapters');var rows=await q('curriculum',[['board','==',C.board],['class','==',cls],['subject','==',sub]]);var cs=uniq(rows,'chapter');if(!cs.length)return empty(sub,'window.ssLearnSubjects(\''+esc(cls).replace(/'/g,"\\'")+'\')');shell('<div class="row"><button class="back" onclick="window.ssLearnSubjects(\''+esc(cls).replace(/'/g,"\\'")+'\')">‹</button><div><h1 style="margin:0">'+esc(sub)+'</h1><div class="muted">Choose a chapter</div></div></div><div class="ss-cards" style="margin-top:16px">'+cs.map(function(c){return '<button class="ss-card" style="text-align:left" onclick="window.ssLearnTopics(\''+esc(cls).replace(/'/g,"\\'")+'\',\''+esc(sub).replace(/'/g,"\\'")+'\',\''+esc(c).replace(/'/g,"\\'")+'\')"><div class="i">📖</div><b>'+esc(c)+'</b><small>Open topics →</small></button>'}).join('')+'</div>')}
async function topics(cls,sub,ch){loading(ch+' · Topics');var rows=await q('curriculum',[['board','==',C.board],['class','==',cls],['subject','==',sub],['chapter','==',ch]]);var ts=uniq(rows,'topic');if(!ts.length)return empty(ch,'window.ssLearnChapters(\''+esc(cls).replace(/'/g,"\\'")+"','"+esc(sub).replace(/'/g,"\\'")+'\')');shell('<div class="row"><button class="back" onclick="window.ssLearnChapters(\''+esc(cls).replace(/'/g,"\\'")+"','"+esc(sub).replace(/'/g,"\\'")+'\')">‹</button><div><h1 style="margin:0">'+esc(ch)+'</h1><div class="muted">Choose a topic</div></div></div><div class="ss-popular" style="margin-top:16px">'+ts.map(function(t){return '<button class="ss-topic" onclick="window.ssLearnLesson(\''+esc(cls).replace(/'/g,"\\'")+"','"+esc(sub).replace(/'/g,"\\'")+"','"+esc(ch).replace(/'/g,"\\'")+"','"+esc(t).replace(/'/g,"\\'")+'\')"><div class="i">💡</div><b>'+esc(t)+'</b><small>Learn topic →</small></button>'}).join('')+'</div>')}
async function lesson(cls,sub,ch,topic){loading(topic+' · Lesson');var rows=await q('curriculum',[['board','==',C.board],['class','==',cls],['subject','==',sub],['chapter','==',ch],['topic','==',topic]]);var r=rows[0];if(!r)return empty(topic,'window.ssLearnTopics(\''+esc(cls).replace(/'/g,"\\'")+"','"+esc(sub).replace(/'/g,"\\'")+"','"+esc(ch).replace(/'/g,"\\'")+'\')');var material=r.lesson||r.content||r.learningMaterial||'';var examples=r.examples||'';var notes=r.revisionNotes||'';var qcount=Array.isArray(r.questionBank)?r.questionBank.length:0;shell('<div class="row"><button class="back" onclick="window.ssLearnTopics(\''+esc(cls).replace(/'/g,"\\'")+"','"+esc(sub).replace(/'/g,"\\'")+"','"+esc(ch).replace(/'/g,"\\'")+'\')">‹</button><div><h1 style="margin:0">'+esc(topic)+'</h1><div class="muted">'+esc(sub)+' · Class '+esc(cls)+'</div></div></div><div class="section"><b>Lesson</b></div><div class="card"><div style="font-size:13px;line-height:1.55">'+esc(material||'Lesson material is being prepared.')+'</div></div>'+(examples?'<div class="section"><b>Examples</b></div><div class="card">'+esc(examples)+'</div>':'')+(notes?'<div class="section"><b>Quick Revision</b></div><div class="card">'+esc(notes)+'</div>':'')+'<div class="section"><b>Practice</b><span>'+qcount+' questions</span></div><button class="btn block" onclick="window.ssLearnPractice(\''+esc(cls).replace(/'/g,"\\'")+"','"+esc(sub).replace(/'/g,"\\'")+"','"+esc(ch).replace(/'/g,"\\'")+"','"+esc(topic).replace(/'/g,"\\'")+'\')">Start Practice →</button>')}
async function practice(cls,sub,ch,topic){loading('Preparing practice');var rows=await q('questions',[['board','==',C.board],['class','==',cls],['subject','==',sub],['chapter','==',ch],['topic','==',topic],['status','==','Published']]);if(!rows.length)rows=await q('questionBank',[['board','==',C.board],['class','==',cls],['subject','==',sub],['chapter','==',ch],['topic','==',topic]]);if(!rows.length){return shell('<div class="row"><button class="back" onclick="window.ssLearnLesson(\''+esc(cls).replace(/'/g,"\\'")+"','"+esc(sub).replace(/'/g,"\\'")+"','"+esc(ch).replace(/'/g,"\\'")+"','"+esc(topic).replace(/'/g,"\\'")+'\')">‹</button><div><h1 style="margin:0">Practice</h1></div></div><div class="card" style="margin-top:18px">Practice questions for this topic are not published yet.</div>')}
var quiz={id:'learn_'+cls+'_'+sub+'_'+ch+'_'+topic,title:topic+' Practice',questions:rows.slice(0,10)};window._ssLearnQuiz=quiz;if(typeof window.startQuiz==='function')window.startQuiz(quiz);else if(typeof window.go==='function')window.go('play')}
window.ssLearnClasses=classes;window.ssLearnSubjects=subjects;window.ssLearnChapters=chapters;window.ssLearnTopics=topics;window.ssLearnLesson=lesson;window.ssLearnPractice=practice;window.learn=function(){classes()};
})();
